-- ============================================================
-- seed_features.sql (AUTO-GENERATED dari server/src/config/features.js)
-- Jangan diedit manual: ubah source di features.js lalu regenerate.
-- INSERT semua feature_key; yang sudah ada akan di-skip (INSERT IGNORE).
-- ============================================================

INSERT IGNORE INTO features (`key`, label, category, description) VALUES
  ('dashboard.view', 'Lihat Dashboard', 'Dashboard', 'Melihat halaman utama dashboard beserta aktivitas terbaru.'),
  ('orders.view', 'Lihat Pesanan', 'Orders', 'Melihat daftar dan detail semua pesanan.'),
  ('orders.create', 'Buat Pesanan', 'Orders', 'Membuat pesanan baru (online / custom customer).'),
  ('orders.custom', 'Custom Order', 'Orders', 'Membuat custom order untuk customer terdaftar.'),
  ('orders.offline', 'Order Offline', 'Orders', 'Membuat pesanan offline di toko.'),
  ('orders.update_status', 'Update Status Pesanan', 'Orders', 'Mengubah status pesanan (misal ke Quality Checking / In Delivery).'),
  ('orders.update_note', 'Catatan Admin', 'Orders', 'Menambah/mengubah catatan admin pada pesanan.'),
  ('orders.update_tracking', 'Update No. Resi', 'Orders', 'Mengisi nomor resi pengiriman pada pesanan.'),
  ('orders.update_delivery', 'Atur Metode Pengiriman', 'Orders', 'Mengatur metode pengiriman (ambil sendiri / kurir).'),
  ('orders.update_pickup', 'Atur Info Pickup', 'Orders', 'Mengatur informasi pickup pesanan.'),
  ('orders.delete', 'Hapus Pesanan', 'Orders', 'Menghapus pesanan yang tidak valid.'),
  ('orders.upload_design', 'Upload Desain', 'Orders', 'Mengupload file desain untuk pesanan.'),
  ('orders.upload_payment', 'Upload Bukti Bayar', 'Orders', 'Mengupload bukti pembayaran pesanan.'),
  ('invoices.view', 'Lihat Invoice', 'Invoices', 'Melihat daftar dan detail invoice.'),
  ('invoices.manage', 'Kelola Invoice', 'Invoices', 'Membuat, mengubah, dan mengatur status pembayaran invoice.'),
  ('invoices.pdf', 'Unduh PDF Invoice', 'Invoices', 'Mengunduh invoice dalam bentuk PDF.'),
  ('customers.view', 'Lihat Customer', 'Customers', 'Melihat daftar customer terdaftar.'),
  ('products.view', 'Lihat Produk', 'Products', 'Melihat daftar dan detail produk.'),
  ('products.manage', 'Kelola Produk', 'Products', 'Membuat, mengubah, dan menghapus produk.'),
  ('products.upload_image', 'Upload Gambar Produk', 'Products', 'Mengupload gambar untuk produk.'),
  ('categories.view', 'Lihat Kategori', 'Categories', 'Melihat daftar kategori produk.'),
  ('categories.manage', 'Kelola Kategori', 'Categories', 'Membuat, mengubah, dan menghapus kategori.'),
  ('reviews.view', 'Lihat Review', 'Reviews', 'Melihat daftar review produk.'),
  ('reviews.delete', 'Hapus Review', 'Reviews', 'Menghapus review dari customer.'),
  ('chats.view', 'Chat Customer', 'Chats', 'Melihat dan membalas percakapan dengan customer.'),
  ('chats.manage', 'Kelola Chat', 'Chats', 'Menyembunyikan / mengelola percakapan chat.'),
  ('dm.view', 'Pesan Staff', 'DM', 'Melihat dan mengirim pesan antar staff (DM).'),
  ('promo.view', 'Lihat Promo', 'Promo', 'Melihat daftar kode promo beserta statistiknya.'),
  ('promo.manage', 'Kelola Promo', 'Promo', 'Membuat, mengubah, dan menghapus kode promo.'),
  ('homepage.manage', 'Kelola Homepage', 'Homepage', 'Mengubah konten homepage: hero banner & item desain.'),
  ('accounts.view', 'Lihat Akun', 'Accounts', 'Melihat daftar semua akun dan detail permission-nya.'),
  ('accounts.manage', 'Kelola Akun & Permission', 'Accounts', 'Mengubah role & permission akun staff.'),
  ('revenue.view', 'Lihat Revenue', 'Revenue', 'Melihat rekap harian dan data revenue.'),
  ('revenue.daily_recap', 'Rekap Harian', 'Revenue', 'Melihat rekap pendapatan harian (kasir).'),
  ('revenue.manage', 'Transaksi Manual', 'Revenue', 'Membuat/mengubah/menghapus transaksi manual.'),
  ('revenue.export', 'Export Revenue', 'Revenue', 'Mengunduh data revenue (CSV/Excel/PDF).'),
  ('revenue.reset', 'Reset Data Revenue', 'Revenue', 'Menghapus seluruh data revenue (hanya Owner).'),
  ('reports.view', 'Lihat Laporan', 'Reports', 'Melihat laporan bulanan, statistik, dan mengunduh laporan.'),
  ('analytics.view', 'Lihat Analytics', 'Analytics', 'Melihat statistik kunjungan, produk dilihat, dan best seller.'),
  ('analytics.reset', 'Reset Data Analytics', 'Analytics', 'Menghapus data analytics (hanya Owner).'),
  ('export.database', 'Export Database', 'Export', 'Mengunduh snapshot seluruh database (JSON).'),
  ('export.uploads', 'Export File Upload', 'Export', 'Mengunduh semua file upload (ZIP).'),
  ('export.all', 'Export Semua Data', 'Export', 'Mengunduh satu paket lengkap database + file upload.'),
  ('offline.new_order', 'Buat Pesanan Baru', 'Offline', 'Membuat pesanan baru dari dashboard offline.'),
  ('offline.order_list', 'Daftar Pesanan', 'Offline', 'Melihat daftar pesanan dari dashboard offline.');
