CREATE TABLE IF NOT EXISTS analytics_visits (
  id         BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  visit_date DATE   NOT NULL UNIQUE,
  count      INT    NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
